apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
#  ports:
#  - protocol: "TCP"
#    port: 80
#    targetPort: 80
#  type: LoadBalancer


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:latest
        imagePullPolicy: Never
        ports:
#        - containerPort: 80

